# Generated by Django 3.0.7 on 2020-07-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200630_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='lol', max_length=150),
            preserve_default=False,
        ),
    ]
