# Generated by Django 3.0.7 on 2020-07-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0004_auto_20200702_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='category', to='categories.Category'),
        ),
    ]
