# Generated by Django 3.0.7 on 2020-07-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200702_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_block_four',
        ),
        migrations.AddField(
            model_name='post',
            name='content_block_one',
            field=models.TextField(default='yo', max_length=415),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content_block_three',
            field=models.TextField(default='yo', max_length=540),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content_block_two',
            field=models.TextField(default='yo', max_length=615),
            preserve_default=False,
        ),
    ]
