# Generated by Django 3.0.7 on 2020-07-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200714_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='post',
            name='sub_image',
            field=models.CharField(default='yo', max_length=300),
            preserve_default=False,
        ),
    ]
